#!/usr/bin/env bash

# Check if git is available
if ! command -v 'git' >/dev/null 2>&1; then
  echo 'Ooops, git not found.'
  echo 'Go to https://git-scm.com for more info.'
  exit 1
fi

# Define repository variables
local_repo="${HOME}/.xcode-snippets"
remote_repo='https://github.com/adrfer/xcode-snippets.git'
local_snippets="${HOME}/Library/Developer/Xcode/UserData/CodeSnippets"

# Backup local files, if any
for folder in "${local_repo}" "${local_snippets}"; do
  if [[ -d "${folder}" ]]; then
    echo -n "Backing up ${folder}..."
    mv -f "${folder%/}"{," copy $(date +%s)"}
    echo ' done.'
  fi
done

# Download and manage remote files
echo -n "Setting up your new arsenal of Swift code snippets..."

if git clone --quiet "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
  rm -rf "${local_snippets}"
  cp -r "${local_repo}/Snippets" "${local_snippets}"
  echo ' done.'
else
  echo 'Ooops, there was an error, try again.'
  exit 1
fi

# Restart and/or open Xcode
if [[ $(pgrep -x '[xX]code') ]]; then
  read -r -p 'Xcode needs to be restarted now, ok (y/n [n])? '

  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    osascript -e 'tell app "Xcode" to quit' >/dev/null 2>&1
  fi
fi

if [[ ! $(pgrep -x '[xX]code') ]]; then
  read -r -p 'Open Xcode now (y/n [n])? '

  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    open -a Xcode
  fi
fi

echo 'All good, enjoy!'
exit 0
