#!/usr/bin/env bash

# Fail fast if not on macOS
if [[ "$(uname)" != 'Darwin' ]]; then
  echo 'Ooops, this runs on macOS only.'
  exit 1
fi

# Check if git is available
if ! command -v 'git' >/dev/null; then
  echo 'Ooops, git not found.'
  exit 1
fi

# Define repository variables
local_repo="${HOME}/.xcode-snippets"
remote_repo='https://github.com/adrfer/xcode-snippets.git'
local_snippets="${HOME}/Library/Developer/Xcode/UserData/CodeSnippets"

# Backup existing files, if any
echo -n "Backing up exising code snippets..."

for folder in "${local_repo}" "${local_snippets}"; do
  if [[ -d "${folder}" ]]; then
    mv -f "${folder%/}"{," copy $(date +%s)"}
  fi
done

echo ' done.'

# Download and setup new files
echo -n "Setting up your arsenal of code snippets..."

if git clone  "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
  rm -rf "${local_snippets}"
  cp -r "${local_repo}/Snippets" "${local_snippets}"
  echo ' done.'
else
  echo
  echo "Ooops, unable to access ${remote_repo}, try again."
  exit 1
fi

# Restart and/or open Xcode
if [[ $(pgrep -x '[xX]code') ]]; then
  read -r -p 'Xcode needs to be restarted. Do it now (y/n [n])? '

  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    osascript -e 'tell app "Xcode" to quit' >/dev/null 2>&1
  fi
fi

if [[ ! $(pgrep -x '[xX]code') ]]; then
  read -r -p 'Open Xcode now (y/n [n])? '

  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    open -a Xcode
  fi
fi

echo 'All good, enjoy!'
exit 0
