#!/usr/bin/env bash

# Confirm uninstall
read -r -p 'Sure to uninstall (y/n [n])? '

if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
  echo 'Ok then, nothing much to see here.'
  exit 0
fi

# Define repository variables
local_repo="${HOME}/.xcode-snippets"
local_snippets="${HOME}/Library/Developer/Xcode/UserData/CodeSnippets"

# Remove existing files, if any
echo -n "Removing existing code snippets..."

for folder in "${local_repo}" "${local_snippets}"; do
  if [[ -d "${folder}" ]]; then
    rm -rf "${folder}"
  fi
done

echo ' done.'

# Restart and/or open Xcode
if [[ $(pgrep -x '[xX]code') ]]; then
  read -r -p 'Xcode needs to be restarted now, ok (y/n [n])? '

  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    osascript -e 'tell app "Xcode" to quit' >/dev/null 2>&1
  fi
fi

if [[ ! $(pgrep -x '[xX]code') ]]; then
  read -r -p 'Open Xcode now (y/n [n])? '

  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    open -a Xcode
  fi
fi

echo 'All good, farewell!'
exit 0
